FROM tensorflow/tensorflow:2.5.0

RUN apt-get update && apt-get install -y \
    libsm6 libxext6 libxrender-dev
RUN pip install -r requirements.txt

COPY . /app
WORKDIR /app

CMD ["python", "object_tracker.py"]

# FROM python:3.7
# RUN \
#  apt-get install -y \
#  wget \
#  unzip \
#  git

# RUN apt-get -y update
# RUN apt-get -y upgrade
# RUN apt-get install -y ffmpeg
# RUN pip3 install --upgrade pip
# RUN pip3 install numpy
# RUN pip3 install tensorflow
# # RUN pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.50.0-py3-none-any.whl
# RUN pip3 install lxml
# RUN pip3 install tqdm
# RUN pip3 install seaborn
# RUN pip3 install pillow
# RUN pip3 install opencv-python
# RUN pip3 install requests
# # RUN pip3 install numba
# RUN pip3 install imutils

# WORKDIR home/abandoned-yolo/
# COPY object_tracker.py /home/abandoned-yolo
# # COPY test_img.jpg /home/
# # RUN git clone https://github.com/pjreddie/darknet

# WORKDIR home/abandoned-yolo/
# RUN wget https://pjreddie.com/media/files/yolov3.weights -P weights/
# WORKDIR /home/abandoned-yolo

# CMD ["python", "object_tracker.py", "--video", "./data/video/macet1.mp4", "--output", "./data/video/macet1.avi"]


# --- kedua ---

# FROM nvidia/cuda:12.2.2-devel-ubuntu22.04
# MAINTAINER ilyassstri 

# RUN apt-get update -y && apt-get install -y python3-pip python3-dev libsm6 libxext6 libxrender-dev


# RUN \
# 	apt-get install -y \
# 	wget \
# 	unzip \
# 	ffmpeg \ 
# 	git

# COPY requirements.txt .

# RUN pip3 install -r requirements.txt

# WORKDIR home/

# # RUN git clone https://github.com/pjreddie/darknet
# # WORKDIR darknet/

# # RUN sed -i 's/GPU=.*/GPU=1/' Makefile 
# # RUN sed -i 's/CUDNN=.*/CUDNN=1/' Makefile && \
# # 	make

# RUN wget https://pjreddie.com/media/files/yolov3.weights -P weights/

# COPY ./data/video/macet1.mp4 /app/data/video/
# COPY ./data/video/macet1.avi /app/data/video/

# WORKDIR /home

# CMD ["python", "object_tracker.py", "--video", "./data/video/macet1.mp4", "--output", "./data/video/macet1.avi"]

# Ketiga
# Gunakan gambar TensorFlow yang sesuai sebagai dasar

